version: "3.8"
services:
  catalog-service:
    depends_on:
      - fluent-bit
      - polar-postgres
      - polar-keycloak
    image: "catalog-service"
    container_name: "catalog-service"
    ports:
      - "9001:9001"
      - "8001:8001"
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb_catalog 
      - POLAR_TESTDATA_ENABLED=true
    logging:
      driver: fluentd
      options: 
        fluentd-address: 127.0.0.1:24224

  order-service:
    depends_on:
    - polar-postgres
    image: "order-service"
    container_name: "order-service"
    ports:
      - "9002:9002"
      - "8002:8002"
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8002
      - SPRING_R2DBC_URL=r2dbc:postgresql://polar-postgres:5432/polardb_order
      - SPRING_FLYWAY_URL=jdbc:postgresql://polar-postgres:5432/polardb_order
      - POLAR_CATALOG_SERVICE_URI=http://catalog-service:9001
      - SPRING_RABBITMQ_HOST=polar-rabbitmq

  dispatcher-service:
    depends_on:
      - polar-rabbitmq
    image: dispatcher-service
    container_name: dispatcher-service
    ports:
      - "9003:9003"
      - "8003:8003"
    environment:
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8002
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_RABBITMQ_HOST=polar-rabbitmq

  edge-service:
    image: edge-service
    container_name: edge_service
    ports:
      - "9000:9000"
      - "8000:8000"
    environment:
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8000
      - CATALOG_SERVICE_URL=http://catalog-service:9001
      - ORDER_SERVICE_URL=http://order-service:9002
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_REDIS_HOST=polar-redis
      - SPA_URL=http://polar-ui:9004
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI=http://host.docker.internal:8080/realms/PolarBookshop

  config-service:
    image: config-service
    container_name: config-service
    ports:
      - "8888:8888"
      - "9888:9888"
    environment:
      - BPL_JVM_THREAD_COUNT=5
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=9888

  polar-ui:
    image: "ghcr.io/polarbookshop/polar-ui:v1"
    container_name: "polar_ui"
    ports:
      - "9004:9004"
    environment:
      - PORT=9004

  polar-postgres:
    image: "postgres:14.4"
    container_name: "polar-postgres"
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

  polar-redis:
    image: "redis:7.0"
    container_name: "polar-redis"
    ports:
      - "6379:6379"

  polar-rabbitmq:
    image: "rabbitmq:3.10-management"
    container_name: "polar-rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  polar-keycloak:
    image: "quay.io/keycloak/keycloak:19.0"
    container_name: "polar-keycloak"
    command: start-dev --import-realm
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=user
      - KEYCLOAK_ADMIN_PASSWORD=password
    ports:
      - "8080:8080"

# Observability

  grafana:
    image: grafana/grafana:9.1.2
    container_name: grafana
    depends_on:
      - loki     
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=user
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - ./observability/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./observability/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./observability/grafana/grafana.ini:/etc/grafana/grafana.ini

  loki:
    image: grafana/loki:2.6.1
    container_name: loki
    depends_on:
      - fluent-bit
    ports:
      - "3100:3100"

  fluent-bit:
    image: grafana/fluent-bit-plugin-loki:2.6.1-amd64
    container_name: fluent-bit
    ports:
      - "24224:24224"
    environment:
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    volumes:
      - ./observability/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf