version: "3.8"
services:
  catalog-service:
    depends_on:
      - polar-postgres
    image: "catalog-service"
    container_name: "catalog-service"
    ports:
      - "9001:9001"
      - "8001:8001"
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb_catalog 
      - POLAR_TESTDATA_ENABLED=true

  order-service:
    depends_on:
    - polar-postgres
    image: "order-service"
    container_name: "order-service"
    ports:
      - "9002:9002"
      - "8002:8002"
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8002
      - SPRING_R2DBC_URL=r2dbc:postgresql://polar-postgres:5432/polardb_order
      - SPRING_FLYWAY_URL=jdbc:postgresql://polar-postgres:5432/polardb_order
      - POLAR_CATALOG_SERVICE_URI=http://catalog-service:9001
  
  polar-postgres:
    image: "postgres:14.4"
    container_name: "polar-postgres"
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

  polar-redis:
    image: "redis:7.0"
    container_name: "polar-redis"
    ports:
      - "6379:6379"
  polar-rabbitmq:
    image: "rabbitmq:3.10-management"
    container_name: "polar-rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf